name: rpi-ipcamera
version: '0.1'
summary: demo IP camera app on Ubuntu for the Raspberry Pi 3
description: |
  A demo IP camera appliance on Ubuntu. Video from a camera attached to the
  Raspberry Pi CSI interface is streamed to the web on port 8000. 

  To watch the video stream go to http://<IP address of your Board>:8000/

grade: stable
confinement: strict

base: core18

architectures:
  - build-on: armhf
    run-on: armhf

apps:
  ipcamera:
    command: ipcamera
    daemon: simple
    plugs:
      - mount-observe
      - network
      - network-bind
      - opengl

parts:
  picamera:
    plugin: python
    python-version: python3
    python-packages:
      - picamera
    build-environment:
      - READTHEDOCS: 'True'
  pilibs:
    plugin: nil
    override-pull: |
      sudo add-apt-repository ppa:ubuntu-raspi2/ppa
      sudo apt-get update
    build-packages:
      - software-properties-common
    after: [ picamera ]
  ipcamera:
    source: .
    plugin: nil
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp ipcamera $SNAPCRAFT_PART_INSTALL/bin/
    stage-packages:
      - libraspberrypi-bin
    after: [ pilibs ]
